### ISSUE TITLE
HTTPError: Response code 404 (Not Found) for getAnimeData()

### ISSUE THREAD

**Issue by johnRambo2k14** [ChrisAlderson/horriblesubs-api#6]
Hi, I really appreciate the work you do and it has helped me out in some of my personal projects! Hoowever, just last night getAnimeData() stopped working.

My Code:

```javascript 
this.horribleSubs.getAllAnime().then((HsRes) => {
               return HsRes;
            }).then((data) => {
                return this.horribleSubs.getAnimeData(data);
            }).then((data) => {
                res.send(data);
            })
            .catch(err => console.error(err));
````

The Error thrown:

```javascript
{ HTTPError: Response code 404 (Not Found)
    at StdError (C:\Users\LOLCAT\Documents\animstream\animstream-backend\node_modules\got\index.js:410:3)
    at C:\Users\LOLCAT\Documents\animstream\animstream-backend\node_modules\got\index.js:454:3
    at stream.catch.then.e (C:\Users\LOLCAT\Documents\animstream\animstream-backend\node_modules\got\index.js:182:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'HTTPError',
  host: 'horriblesubs.info',
  hostname: 'horriblesubs.info',
  method: 'GET',
  path: '/undefined?',
  protocol: 'https:',
  url: 'https://horriblesubs.info/undefined',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers:
   { date: 'Sat, 30 Sep 2017 11:43:40 GMT',
     'content-type': 'text/html; charset=UTF-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'set-cookie': [ '__cfduid=d65ea6297084293854bcaf026ece578e71506771820; expires=Sun, 30-Sep-18 11:43:40 GMT; path=/; domain=.horriblesubs.info; HttpOnly' ]
,
     vary: 'Cookie',
     expires: 'Wed, 11 Jan 1984 05:00:00 GMT',
     'cache-control': 'no-cache, must-revalidate, max-age=0',
     link: '<http://horriblesubs.info/wp-json/>; rel="https://api.w.org/"',
     server: 'cloudflare-nginx',
     'cf-ray': '3a66ed037dfe6b91-LHR',
     'content-encoding': 'gzip' } }
```

I would assume changed their DOM in some way which could be the reason throwing this error?

**Comment by ChrisAlderson** [comment]
This is because the `getAllAnime` method returns an array with objects in them. The `getAnimeData` takes an object out the array of objects as a parameter. You can see it in the example included in the readme file of this repo.

```js
// Get all available shows on horriblesubs.
horriblesubs.getAllAnime().then(res => {
  const [ data ] = res // same as: const data = res[0]
  console.log(data)

  // Get data including episodes from horriblesubs.
  return horriblesubs.getAnimeData(data)
}).then(res => console.log(res))
  .catch(err => console.error(err))
```

**Comment by johnRambo2k14** [comment]
Oh man thank you, clearly I haven't had my morning coffee yet 😅
